### PR TITLE
Allow running fpm as root

### PR DESCRIPTION
**Pull request by michaeljs1990**
For one reason or another in my environment it is much easier to run this as root... Mostly due to permissions around my NAS system. This will allow people if they so dare to set the PUID to 0 and run this container.

[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by michaeljs1990** [comment]
I have pushed michaeljs1990/rutorrent to my dockerhub as well although it's easy enough to build locally.

Additionally if we are adamantly against running as root for whatever reason I can add update the readme and add some error checking to throw if a PUID of 0 is set. Currently you have to dig around in /var/logs to find what is happening.

**Comment by sparklyballs** [comment]
we don't recommend running our containers as root and this seems an edge case to me

**Comment by soruly** [comment]
When running with podman (rootless container), if we define `PUID=1000`, the UID would be run as 100999 on host, which is incorrect. In order to correctly map it, we need to run as `PUID=0` which maps correctly to host uid who starts the container.
https://discuss.linuxcontainers.org/t/looking-for-clarification-about-subuid-gid/630/3

libpod actually recommends running containers with UID=0
https://github.com/containers/libpod/issues/3421#issuecomment-505209095

**Comment by xSke** [comment]
Not allowing this makes this container useless under Docker for Windows, as bind mounted directories are only writable by root (and this, as far as I can tell, can't be changed at all).

**Pull request closed without merging**
