### PR TITLE
Add material design theme

### PR DESCRIPTION
**Pull request by onedr0p**

### CODE REVIEW

**Comment by onedr0p** [comment]
#29

**Comment by aptalca** [comment]
I'm looking into implementing a system where a user can add any custom plugin they want. But no promises ;)

**Comment by sparklyballs** [comment]
adds no value as far as i can see.

**Comment by onedr0p** [comment]
Dafuk? Could you at least allow us to set a custom theme by exposing the theme directory on ruTorrent?

**Pull request closed without merging**
