### PR TITLE
Fix rtorrent shut down

### LINKED ISSUE #57: Lockfile not deleted on `docker stop`
When running `docker stop` on this container, the rtorrent lock file is not deleted. This means that on subsequent starts of the container, rtorrent fails to execute (because the lock file still exists). I have to manually remove it between restarts.

Is this a known issue? Can it be addressed by sending some custom signal (`docker kill --signal=something`)?

### LINKED ISSUE #58: rtorrent process not gracefully terminated
When running docker stop on this container, the rtorrent lock file is not deleted. 

The fact this lock file is left behind indicates rtorrent isn't gracefully shutting down. This can cause issues with state data in rtorrent.

### PR DESCRIPTION
**Pull request by aptalca**
Do we need the tail log in the service file? Or was it there just to keep the service script in the foreground. If it's needed for some reason, I can add it as a separate service, because in its current form, it gets in the way of trapping the sigterm and forwarding it to the rtorrent process.

fixes #58 
fixes #57

### CODE REVIEW

**Comment by sparklyballs** [comment]
it's there to keep the service foreground and this is unneeded complexity to fix a problem that doesn't exist

**Comment by aptalca** [comment]
Oh, good. So with this pr, we just replace the logging with trap/wait and the process remains active in the foreground. 

This pr is fixing cron, php-fpm and rtorrent not being stopped by `s6-svc -d`

**Comment by adamwinn** [comment]
Thank you for this fix.  I was encountering this issue

**Comment by fidelix** [comment]
Please merge this PR.

**Comment by deed02392** [comment]
@adamwinn @aptalca @Fidelix: @sparklyballs doesn't think this is a problem, maybe because he doesn't understand it or because he doesn't care :-) I already tried to get this fix pulled back in August: https://github.com/linuxserver/docker-rutorrent/pull/59

Other maintainers get it but still nothing has been done. I am using a personal fork for now.

**Comment by fidelix** [comment]
@deed02392 I'm using a personal fork as well, where I included the ability to run custom themes and plugins too.

I mean, it was so easy doing it (and backwards-compatible) that I don't understand why this isn't included even though it was already requested before.

**Comment by deed02392** [comment]
@Fidelix ah sweet, I've just taken a look and there's a PR here for it too: https://github.com/linuxserver/docker-rutorrent/pull/41 from 9 months ago...

**Comment by sparklyballs** [comment]
@deed02392 i understand the PR and do care about our images but this is "fixing" a problem that doesn't actually exist and i don't appreciate your childish sniping

**Comment by deed02392** [comment]
@sparklyballs "problem that doesn't actually exist" 
So how do you explain the multitude of people raising these issues and PRs?

**Comment by sparklyballs** [comment]
metooism 

has anyone lost any data ?

**Comment by deed02392** [comment]
I think people are discovering the issue on their own, hence the new PR even though my original PR addressed the same thing. I'm not sure how the issue has presented for other people.

**Comment by alex-phillips** [comment]
This fix is included in the new rewrite here: https://github.com/linuxserver/docker-rutorrent/pull/94

**Pull request closed without merging**
