### PR TITLE
attempt to fix plugins not working until first webui launch

### LINKED ISSUE #133: Autotools plugin does not work until Web UI is opened for first time
The Autotools plugin doesn't work with a new or restarted container until the Web UI is opened for the first time. Torrents that are added before that will have no label and won't be moved.

The issue seems to be caused by this line in the rtorrent config file: 

https://github.com/linuxserver/docker-rutorrent/blob/13ab52152de2d9446e2497b1e827b25573c473df/root/defaults/rtorrent.rc#L1

According to the rutorrent documentation (https://github.com/Novik/ruTorrent/wiki/Plugins#starting-plugins-with-rtorrent) the command should be `execute2`. The path to the startup script also seems to be outdated. 

So I changed the line in my config file to this:
~~~
execute2 = {sh,-c,/usr/bin/php7 /app/rutorrent/php/initplugins.php &}
~~~

Unfortunately this still doesn't work. 

Manually running `/usr/bin/php7 /app/rutorrent/php/initplugins.php &` inside the container actually works.

### PR DESCRIPTION
**Pull request by ThatNerdyPikachu**
fixes #133

## Description:
Changes ``execute`` to ``execute2``, since this isn't a version older than 0.9, see ruTorrent wiki.

## Benefits of this PR and context:
#133

## How Has This Been Tested?
n/a

### CODE REVIEW

**Comment by ThatNerdyPikachu** [comment]
As I said in the PR, I don't know how to actually test this. I made these changes locally to my configuration, and everything seems to work.

Ref https://github.com/rakshasa/rtorrent/wiki/COMMAND-Execute https://github.com/Novik/ruTorrent/wiki/Plugins#starting-plugins-with-rtorrent

**Comment by nemchik** [comment]
Have you followed the local build instructions? https://github.com/linuxserver/docker-rutorrent/blob/master/README.md#building-locally

You should be able to confirm that you're running your local build and confirm that your changes work and then let us know.

If you have a specific plugin you're testing that you could link here it would help us to review and test as well.

**Comment by j0nnymoe** [comment]
@ThatNerdyPikachu also, LinuxServer-CI tests each PR and builds an image you can test, see the report links it posted.

**Comment by ThatNerdyPikachu** [comment]
Initial tests done. Will do more and report back.

**Comment by ThatNerdyPikachu** [comment]
I can't test this, but can someone test with AutoTools?

Procedure:
- Enable AutoTools autoadd from directory
- Restart container, and do not open WebUI
- Add torrents to folder
- See if torrents get added (check a few minutes later)

**Comment by ThatNerdyPikachu** [comment]
Everything tested, this is safe to merge.

**Comment by ThatNerdyPikachu** [comment]
Bump?

**Comment by alex-phillips** [comment]
LGMT

**Comment by alex-phillips** [comment]
LGMT

**Pull request merged**
